# Backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;

# Opacity
active-opacity = 0.7;
inactive-opacity = 0.5;
frame-opacity = 1;
inactive-opacity-override = false;
opacity-rule = [
    "100:class_g = 'firefox'",
	"100:class_g = 'mpv'",
	"100:class_g = 'code-oss'",
	"100:class_g = 'Minecraft 1.18.2'",
	"100:class_g = 'Blender'",
    "100:class_g = 'xfce4-screenshooter'",
    "100:class_g = 'Unity'",
	"100:class_g = 'Spotify' && focused",
	"80:class_g = 'Spotify' && !focused",
	"100:class_g = 'discord' && focused",
	"80:class_g = 'discord' && !focused",
	"80:class_g = 'obsidian' && focused"
];

# Blur
blur-background = false;
blur-background-exclude = [
	"window_type = 'dock'",
];
blur-method = "dual_kawase";
blur-strength = 8;

# Fading
fading = true;
fade-delta = 4;
no-fading-open-close = false;
no-fading-destroyed-argb = false;

# Other
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
vsync = true;
dbe = false;
unredir-if-possible = false;
focus-exclude = [ ];
detect-transient = true;
detect-client-leader = true;

# Window type settings
wintypes:
{
	dock = {
		shadow = false;
	};
};

# Shadows
shadow = false;
shadow-radius = 12;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;

shadow-exclude = [
	"name = 'Notification'"
];

# Rounded corners
corner-radius = 5;
rounded-corners-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'"
];

